### ISSUE TITLE
Kernel cannot add device

### ISSUE THREAD

**Issue by fossum** [h0tw1r3/dvbhdhomerun#7]
After getting your code to compile and load into my computer I noticed the dmesg had some errors in it. Seems to be a bad pointer somewhere in your code. I've attached my dmesg output, hopefully you know how to decipher it.

I did see that there is a failure early on

```sh
[   16.531894] DVB: registering new adapter (HDHomeRun)
[   16.531896] vmalloc: allocation failure: 18446743833813787648 bytes
[   16.531897] userhdhomerun: page allocation failure: order:0, mode:0xd2
```

I tried increasing my vmalloc in grub (not sure if it worked), but I didn't increase it by 18,446,743 terabytes either.

[dmesg.txt](https://github.com/h0tw1r3/dvbhdhomerun/files/67863/dmesg.txt)

System Info:
Running in ESXi system
Fresh install of Ubuntu 15.04 x64

Steps to reproduce:
1. Install Ubuntu
2. Install compile tools
3. Run dpkg-buildinstall -i

**Comment by Liontooth** [comment]
I get exactly the same error on a Debian Jessie installation from yesterday. A workaround is to block the module from loading in boot by adding this to the file /etc/modprobe.d/blacklist-dvb_hdhomerun.conf:

install dvb_hdhomerun /bin/true

After boot, uncomment this line and try "modprobe dvb_hdhomerun" manually; that works for me. That said, I still get a kernel oops on userhdhomerun.

**Comment by h0tw1r3** [comment]
Can you try the latest checkout (fa3795a1ce28751a34d5ee73b62ef8b24405f44b)?

**Comment by fossum** [comment]
Dear Jesus, that worked. How'd you get 4-5 commits in already!? Anywho, thanks for the support. If you need someone to attempt this on Fedora or Ubuntu, I could help out.

**Comment by fossum** [comment]
Umm... actually I take that back. It worked on my test fresh install box, but I'm still having issues with the production system. I'm going to update to the Silicon Dust libhdhome run and see if that helps. PS - I think Liontooth's fix is needed on top of this code update.

**Comment by h0tw1r3** [comment]
I just tested 4.2.5 kernel (Fedora). Everything builds, modules load, and userspace adds the DVB devices (tested HDHR3-US).

Just a guess, but perhaps dkms did not rebuild? Try pulling master again (commit a8837cf) and rebuilding the packages. Bumped the debian version which should trigger a dkms rebuild.

**Comment by fossum** [comment]
K, so verified a8837cf changeset and deleted all ../hdhomerun-* files. Then `dpkg-buildpackage -b`, `cd ..`, `sudo dpkg -i dvbhdhomerun-*`, `sudo shutdown -r now`, `dmesg`

Output: [dmesg.txt](https://github.com/h0tw1r3/dvbhdhomerun/files/70492/dmesg.txt)

**Comment by fossum** [comment]
Seems the hdhomerun_control doesn't have the right permissions:

```sh
ericfoss@mediaserver:~$ ls -l /dev/hd*
-rw-r--r-- 1 root root 0 Dec 22 21:40 /dev/hdhomerun_control
ericfoss@mediaserver:~$
```

Even though I have the /lib/udev/rules.d/59-dvbhdhomerun-utils.rules file

```sh
KERNEL=="hdhomerun_data[0-9]*", GROUP="video"
KERNEL=="hdhomerun_control", GROUP="video"
```

**Comment by h0tw1r3** [comment]
Personally verified working on Ubuntu 15.10.

Check dkms to make sure you're using the correct modules.

    dvbhdhomerun, 0.0.16+nmu4, 4.2.0-22-generic, x86_64: installed

If it looks the same, try purging the installed packages, and building from source again.

**Comment by Liontooth** [comment]
If the device node /dev/hdhomerun_control is incorrect, remove it and reinsert the dvb_hdhomerun module to recreate it.

The patches work; I rebuilt dvbhdhomerun from the latest version on Debian Jessie with a 3.16.0-4-amd64 kernel. Running userhdhomerun works, and the devices are seen by tvheadend. Very cool!
